services:
  web-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./src:/home/nurbek/src

    environment:
      - DB_HOST=db
      - DB_NAME=TestP
      - DB_USER=nurbek
      - DB_PASS=F0Lb3AHE@nc

    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

    depends_on:
      - db

  db:
    image: postgres:15.1-alpine
    environment:
      - POSTGRES_DB=TestP
      - POSTGRES_USER=nurbek
      - POSTGRES_PASSWORD=F0Lb3AHE@nc