# Generated by Django 4.2.14 on 2024-10-01 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Порода')),
                ('img', models.ImageField(upload_to='images/breeds/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Порода',
                'verbose_name_plural': 'Породы',
            },
        ),
        migrations.CreateModel(
            name='Cats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('color', models.CharField(verbose_name='Цвет')),
                ('age', models.DateField(verbose_name='Дата рождения')),
                ('description', models.TextField(verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('breed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cats.breeds', verbose_name='Порода')),
            ],
            options={
                'verbose_name': 'Котенок',
                'verbose_name_plural': 'Котенки',
            },
        ),
        migrations.CreateModel(
            name='CatImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/cats/', verbose_name='Изображение')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='img', to='cats.cats')),
            ],
        ),
    ]
