# Generated by Django 4.2.14 on 2024-10-01 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cats', '0002_cats_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cats',
            name='img',
            field=models.ImageField(default=1, upload_to='images/cats/', verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cats',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='CatImages',
        ),
    ]
